# Index and selecting data

In [1]:
import xarray as xr
import numpy as np
import pandas as pd

In [2]:
da = xr.DataArray(
    np.random.rand(4, 3),
    [
        ("time", pd.date_range("2000-01-01", periods=4)),
        ("space", ["IA", "IL", "IN"]),
    ],
)
da

<xarray.DataArray (time: 4, space: 3)>
array([[0.99615542, 0.47934038, 0.09854804],
       [0.60759663, 0.74557287, 0.66228189],
       [0.10094564, 0.25156307, 0.69642501],
       [0.92861876, 0.39202578, 0.10793906]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [3]:
da[:2] # 左闭右开的直接引用

<xarray.DataArray (time: 2, space: 3)>
array([[0.99615542, 0.47934038, 0.09854804],
       [0.60759663, 0.74557287, 0.66228189]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02
  * space    (space) <U2 'IA' 'IL' 'IN'

## Index with dimension names
使用维度名称，我们不必依赖维度顺序，可以显式使用它们来切片数据。有两种方法可以做到这一点：


1. 使用字典作为数组位置或基于标签的数组索引的参数：

In [4]:
da.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [5]:
da[dict(space=0, time=slice(None, 2))]

<xarray.DataArray (time: 2)>
array([0.99615542, 0.60759663])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02
    space    <U2 'IA'

In [6]:
da.sel(dict(space='IA'))

<xarray.DataArray (time: 4)>
array([0.99615542, 0.60759663, 0.10094564, 0.92861876])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
    space    <U2 'IA'

In [7]:
de.sel?

Object `de.sel` not found.
